export const ACTION = 'ACTION';
export const SET_SHOP_PAGE = 'SET_SHOP_PAGE'
export const CODE_REQUEST_SUCCESS = 'CODE_REQUEST_SUCCESS'
export const CODE_REQUEST_FAILED = 'CODE_REQUEST_FAILED'
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAIL = 'VERIFY_CODE_FAIL'
export const EDIT_USER_INFO = 'EDIT_USER_INFO'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const SET_LOADER = 'SET_LOADER';
export const UPDATE_FAILED = 'UPDATE_FAILED';


export const OPEN_FORM = 'OPEN_FORM';
export const QUIT_ACCOUNT = 'QUIT_ACCOUNT';
export const OPEN_SCANER = 'OPEN_SCANER';
export const SET_SCANER_FORM = 'SET_SCANER_FORM'

export const SHOW_MAP = 'SHOW_MAP';
export const SET_SPONSORY_PAGE = 'SET_SPONSORY_PAGE'



export const SET_CHECKS = 'SET_CHECKS'
export const SHOW_CHECK_LIST = 'SHOW_CHECK_LIST'
export const SET_CHECKS_FAILED = 'SET_CHECKS_FAILED'


export const SET_WINNERS_LIST = 'SET_WINNERS_LIST'
export const SET_WINNERS_LIST_FAILED = 'SET_WINNERS_LIST_FAILED'

export const SET_SHOP = 'SET_SHOP'
